name: CI

on:
  push:
    branches:
      - '!main'
    paths:
      - values/protected-app-specific/**

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v12
        with:
          github-token: ${{github.token}}
          diffDoesNotContain: "name: |type: |subdomainModifiers: "
