name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          protected-app-specific:
            - 'values/protected-app-specific/**'
            
    - name: Checking protected area
      if: steps.filter.outputs.protected-app-specific == 'true'
      uses: JJ/github-pr-contains-action@releases/v12
      with:
        github-token: ${{github.token}}
        diffDoesNotContain: "name: |type: |cpu: |memory:"
