name: CI

on:
  pull_request:
    branches:
      - main


jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v12
        with:
          github-token: ${{github.token}}
          diffDoesNotContain: "name: |type: "
